### ISSUE TITLE
Support for WordPress PHP coding standards

### ISSUE THREAD

**Issue by ziodave** [codeclimate/codeclimate-phpcodesniffer#15]
Hello,

PHP_CodeSniffer doesn't support WordPress coding standards oob, https://github.com/squizlabs/PHP_CodeSniffer/tree/master/CodeSniffer/Standards.

However these are available here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

Is it possible to add support for WordPress coding standards?

Thanks!

**Comment by soderlind** [comment]
+1

**Comment by 75nineteen** [comment]
+2

**Comment by vinnylabarbera** [comment]
+1

**Comment by AlisonLapidus** [comment]
+1

**Comment by ABaldwinHunter** [comment]
Hi @ziodave Thanks for your feedback! We have exploring that feature on our roadmap.

**Comment by josephdpurcell** [comment]
I believe this is resolved in https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/34.

**Comment by dblandin** [comment]
Hey @ziodave,

Thanks to the contributions of @josephdpurcell in #34, we now vendor WordPress coding standards within the engine! These standards are available today via the CLI or [codeclimate.com]().

The README has been updated with a [list of supported standards](https://github.com/codeclimate/codeclimate-phpcodesniffer#supported-coding-standards). You can enable the Wordpress standards by updating your `codeclimate.yml` configuration file:

```yaml
phpcodesniffer:
  enabled: true
  config:
    standard: "Wordpress"
```

Thanks for your patience and 👏  to @josephdpurcell!
