### ISSUE TITLE
WordPress Coding Standards 0.10.0

### ISSUE THREAD

**Issue by soderlind** [codeclimate/codeclimate-phpcodesniffer#43]
Just released: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/0.10.0

How do I update the engine ?

**Comment by dblandin** [comment]
Hey @soderlind,

You can bump the WPCS version number in the Composer file [here](https://github.com/codeclimate/codeclimate-phpcodesniffer/blob/master/composer.json#L7) and update the `composer.lock` file.

There is also a check -> remediation point mapping in the `Sniffs.php` file [here](https://github.com/codeclimate/codeclimate-phpcodesniffer/blob/master/Sniffs.php) if the update introduces new checks.

Once that's merged, I can push out a new engine release.

**Comment by dblandin** [comment]
Hey @soderlind,

I just released an update to this engine which [includes a version bump](https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/47) of the WP-Coding-Standards package to v0.10.0.

Thanks for the nudge on this!

**Comment by soderlind** [comment]
Excellent, thanks !
