### ISSUE TITLE
Please add Yii2 coding standard

### ISSUE THREAD

**Issue by cmoeke** [codeclimate/codeclimate-phpcodesniffer#48]
Please add the Yii2-Framework (http://www.yiiframework.com/) coding standard to use it for extensions.

The coding standard can found here:
https://github.com/yiisoft/yii2-coding-standards

**Comment by josephdpurcell** [comment]
I created issue #49 to hopefully make this more dynamic.

In the mean time, I created PR #50 to add the Yii2 standard.

**Comment by dblandin** [comment]
Hey @cmoeke,

I just released a new version of the engine with support for the Yii2 framework which is now available via codeclimate.com and the CLI.

Thanks for the nudge and thanks to @josephdpurcell for the PR!

**Comment by josephdpurcell** [comment]
I forgot to add the Yii2 to the list of installed standards like was done for Drupal and Wordpress: https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/34/files#diff-3254677a7917c6c01f55212f86c57fbfR12

Re-opening this issue until that is addressed.

**Comment by josephdpurcell** [comment]
This feature is merged. Closing this ticket.
