### ISSUE TITLE
Support Magento coding standards

### ISSUE THREAD

**Issue by josephdpurcell** [codeclimate/codeclimate-phpcodesniffer#51]
Add https://github.com/magento-ecg/coding-standard as a coding standard

**Comment by siment** [comment]
As an addition to above mentioned coding standard I would also suggest that the following Magento sniffs become available:

- [Magento Extension Quality Program Coding Standard](https://github.com/magento/marketplace-eqp) for Magento 1 and Magento 2

I would also like to mention the code sniffs that are included with Magento framework ([GitHub link](https://github.com/magento/magento2/blob/develop/dev/tests/static/testsuite/Magento/Test/Php/_files/phpcs/ruleset.xml)), but they are not compatible with squizlabs/php_codesniffer version 2. At this time, Code Climate uses phpcs v2.7.1.

IMO the sniffs from **[Magento Extension Quality Program Coding Standard](https://github.com/magento/marketplace-eqp)** is a good start. After all, most Magento developers create *extensions*, not Magento framework changes.

**Comment by josephdpurcell** [comment]
Thank you for this great feedback, @siment! Very good thoughts, and I agree--more people will be doing extension work than core work. I'm happy to help make this change.

Is it installable via composer? I don't see it on packagist: https://packagist.org/search/?q=magento%2Fmarketplace-eqp

**Comment by siment** [comment]
@josephdpurcell It is installable via composer. Name is **magento/marketplace-eqp**.

You must make sure that you have added the Magento repository to your composer.json file similar to this:

```js
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
```

And then authenticate to the Magento repo using your access key that you can find on your Magento account.

**Comment by josephdpurcell** [comment]
@siment Unfortunately, it looks like Magento's repository requires authentication. The Code Climate team may be able to create an account and specify an authentication key, however, that has management overhead.

If you know the maintainers of https://github.com/magento/marketplace-eqp, perhaps suggest to them to put the repository on packagist.org to make it publicly available.

In the mean time, I manually set a repository that points to the GitHub repo like so: https://github.com/codeclimate/codeclimate-phpcodesniffer/pull/54/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R2

Please take a look and let me know if there are any improvements or changes you'd like to make. Otherwise, I think we're set!

**Comment by josephdpurcell** [comment]
@siment PR #54 is merged. If I see activity on it getting rolled out to production I'll write back.

Once that's out, let me know if you have any issues.

In the mean time, thank you so much for this contribution and if you'd like to contribute through helping give feedback on other issues that is welcome!

**Comment by dblandin** [comment]
@josephdpurcell @siment I rolled out an update to production yesterday which includes the updates in #54. Should be available via the CLI and codeclimate.com now 👍

**Comment by dblandin** [comment]
Going to go ahead and close this issue. Thanks for the contribution!
