### ISSUE TITLE
WordPress Coding Standard 0.14

### ISSUE THREAD

**Issue by soderlind** [codeclimate/codeclimate-phpcodesniffer#68]
Is the [latest release of wpcs](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/master/CHANGELOG.md#0140---2017-11-01) included?

I'm getting a warning, `When an array uses associative keys, each value should start on a new line`. This is fixed in the latest release. It's only required for multi-item associative arrays.

**Comment by larkinscott** [comment]
Hi @soderlind! We just bumped our plugin to the latest version of wpcs (0.14.0), so you should be all set. Thanks!

**Comment by dblandin** [comment]
Going to go ahead and close this issue. Thanks!
