### ISSUE TITLE
Please add PSR12 coding standard

### ISSUE THREAD

**Issue by abenevaut** [codeclimate/codeclimate-phpcodesniffer#77]
> This specification extends, expands and replaces PSR-2, the coding style guide and requires adherence to PSR-1, the basic coding standard.

https://www.php-fig.org/psr/psr-12/

codeclimate output when refreshing a project:
<img width="1052" alt="Capture d’écran 2020-01-23 à 14 30 58" src="https://user-images.githubusercontent.com/1134021/72988677-047bff00-3ded-11ea-8a79-f03cb34ed796.png">

**Comment by efueger** [comment]
Thanks @abenevaut - just added this to our internal queue. 👌

**Comment by beleidy** [comment]
@efueger  Is it possible to see somewhere the internal queue to get a sense of when this might be supported? Thank you

**Comment by fede-moya** [comment]
@beleidy we have recently launched a `beta` channel for supporting this. @efueger I think we can close this one.
